package iRaptorPackage;

import domain.DBUtil;



/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * raptorAddGUI.java
 *
 * Created on Mar 24, 2009, 1:03:04 PM
 */

/**
 *
 * @author Gun Jack
 */
public class raptorAddGUI extends javax.swing.JFrame {

    /** Creates new form raptorAddGUI */
    public raptorAddGUI() {
        initComponents();


    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ratingField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ohGod2 = new javax.swing.JButton();
        ohGod = new javax.swing.JButton();
        addItemButton = new javax.swing.JButton();
        typeComboBox = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        titleField = new javax.swing.JTextField();
        yearReleasedField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        notesArea = new javax.swing.JTextArea();
        closeButton = new javax.swing.JButton();
        genreField = new javax.swing.JTextField();
        directorLabel = new javax.swing.JLabel();
        isbnLabel = new javax.swing.JLabel();
        publisherLabel = new javax.swing.JLabel();
        directorField = new javax.swing.JTextField();
        publisherField = new javax.swing.JTextField();
        isbnField = new javax.swing.JTextField();
        
        /*---------------------------------------------------------------
         * FOR TESTING PURPOSES (do not delete
         */
        addItemButton.setName("add item done button");
        typeComboBox.setName("add item combo box");
        titleField.setName("title text field");
        //-----------------------------------------------------------------

        setTitle("Add Item");

        jLabel1.setText("Type");

        jLabel2.setText("Genre");

        jLabel3.setText("Rating");

        jLabel4.setText("Notes");

        ohGod2.setVisible(false);
        ohGod2.setText("Raptor Recommends");
        ohGod2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ohGod2ActionPerformed(evt);
            }
        });

        ohGod.setVisible(false);
        ohGod.setText("Raptor Recommends");
        ohGod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ohGodActionPerformed(evt);
            }
        });

        addItemButton.setText("Add Item");
        addItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addItemButtonActionPerformed(evt);
            }
        });

        typeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Movie", "Book", "Game", "CD" }));
        typeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeComboBoxActionPerformed(evt);
            }
        });

        jLabel7.setText("Year Released");

        jLabel6.setText("Name");

        notesArea.setColumns(20);
        notesArea.setRows(5);
        notesArea.setMinimumSize(new java.awt.Dimension(6, 20));
        notesArea.setPreferredSize(new java.awt.Dimension(6, 20));
        jScrollPane2.setViewportView(notesArea);

        closeButton.setVisible(true);
        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        directorLabel.setText("Director/Artist");
        directorLabel.setVisible(true);

        isbnLabel.setText("ISBN");
        isbnLabel.setVisible(false);

        publisherLabel.setText("Publisher");
        publisherLabel.setVisible(false);

        directorField.setVisible(true);
        directorField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                directorFieldActionPerformed(evt);
            }
        });

        publisherField.setVisible(false);

        isbnField.setVisible(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(directorLabel)
                                    .addComponent(jLabel4)
                                    .addComponent(publisherLabel)
                                    .addComponent(isbnLabel))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(typeComboBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ratingField, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                                            .addComponent(titleField, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                                            .addComponent(genreField, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(isbnField, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(publisherField, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(directorField, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(yearReleasedField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ohGod2)
                                            .addComponent(ohGod)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(addItemButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(closeButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(typeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(titleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ohGod2)
                    .addComponent(genreField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ratingField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ohGod))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(yearReleasedField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(directorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(directorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(publisherLabel)
                    .addComponent(publisherField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(isbnLabel)
                    .addComponent(isbnField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addItemButton)
                            .addComponent(closeButton)))
                    .addComponent(jLabel4))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addItemButtonActionPerformed
          Object selectedMediaType = typeComboBox.getSelectedItem();
          String genreType = genreField.getText();
          String rating = ratingField.getText();
          int intRating = Integer.parseInt(rating);
          String title = titleField.getText();
          String yearReleased = yearReleasedField.getText();
          int intYearReleased = Integer.parseInt(yearReleased);
          String isbn = isbnField.getText();
          String publisher = publisherField.getText();
          String director = directorField.getText();
          String notes = notesArea.getText();
          System.out.println(genreType);
          if(selectedMediaType == "Movie"){
            domain.DVD d = domain.DomainUtil.addDVD(title);
            d.setDirectorName(director);
            d.setGenre(genreType);
            d.setNotes(notes);
            d.setRating(intRating);
            d.setYear(intYearReleased);
          }
          if(selectedMediaType == "Book"){
            domain.Book b = domain.DomainUtil.addBook(title);
            b.setGenre(genreType);
            b.setRating(intRating);
            b.setYear(intYearReleased);
            b.setNotes(notes);
            b.setPublisher(publisher);
            b.setIsbn(isbn);
          }
          if(selectedMediaType == "CD"){
            domain.CD c = domain.DomainUtil.addCD(title);
            c.setGenre(genreType);
            c.setNotes(notes);
            c.setRating(intRating);
            c.setYear(intYearReleased);

          }
          if(selectedMediaType == "Game"){
            domain.VideoGame VG = domain.DomainUtil.addVideoGame(title);
            VG.setGenre(genreType);
            VG.setNotes(notes);
            VG.setRating(intRating);
            VG.setYear(intYearReleased);
            }
          

}//GEN-LAST:event_addItemButtonActionPerformed

    private void ohGod2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ohGod2ActionPerformed

    }//GEN-LAST:event_ohGod2ActionPerformed

    private void ohGodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ohGodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ohGodActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        this.dispose();
}//GEN-LAST:event_closeButtonActionPerformed

    private void typeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeComboBoxActionPerformed
      Object selectedMediaType = typeComboBox.getSelectedItem();
      if(selectedMediaType == "Book"){
              directorField.setVisible(false);
              isbnField.setVisible(true);
              publisherField.setVisible(true);
              isbnLabel.setVisible(true);
              publisherLabel.setVisible(true);
              directorLabel.setVisible(false);
      }
      if(selectedMediaType == "Movie"){
              isbnLabel.setVisible(false);
              publisherLabel.setVisible(false);
              directorLabel.setVisible(true);
              directorField.setVisible(true);
              isbnField.setVisible(false);
              publisherField.setVisible(false);
      }
      if(selectedMediaType == "CD"){
              directorLabel.setVisible(false);
              isbnLabel.setVisible(false);
              publisherLabel.setVisible(false);
              directorField.setVisible(false);
              isbnField.setVisible(false);
              publisherField.setVisible(false);
      }
      if(selectedMediaType == "Game"){
              directorLabel.setVisible(false);
              isbnLabel.setVisible(false);
              publisherLabel.setVisible(false);
              directorField.setVisible(false);
              isbnField.setVisible(false);
              publisherField.setVisible(false);
      }
    }//GEN-LAST:event_typeComboBoxActionPerformed

    private void directorFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_directorFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_directorFieldActionPerformed

    /**
    * @param args the command line arguments
    */

    // Varies declaration - do not modify//GEN-BEGIN:varies
    private javax.swing.JButton addItemButton;
    private javax.swing.JButton closeButton;
    private javax.swing.JTextField directorField;
    private javax.swing.JLabel directorLabel;
    private javax.swing.JTextField genreField;
    private javax.swing.JTextField isbnField;
    private javax.swing.JLabel isbnLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea notesArea;
    private javax.swing.JButton ohGod;
    private javax.swing.JButton ohGod2;
    private javax.swing.JTextField publisherField;
    private javax.swing.JLabel publisherLabel;
    private javax.swing.JTextField ratingField;
    private javax.swing.JTextField titleField;
    private javax.swing.JComboBox typeComboBox;
    private javax.swing.JTextField yearReleasedField;
    // End of varies declaration//GEN-END:varies

}
