package domain;


import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 * Represents a VideoGame from the database.
 * @author Corey
 *
 */
public class VideoGame extends Item {
	
	private final int NUMFIELDS = 0;
	
	/**
	 * Generates a new VideoGame instance and adds it to the database. 
	 * @param title The title of the new VideoGame.
	 */
	protected VideoGame(String title) {
		super(title);
		
		String sqltxt = "INSERT INTO VideoGame (itemId) VALUES (?);";
		Connection conn = DBUtil.getConnection();
		
		try {
			PreparedStatement ps = conn.prepareStatement(sqltxt);
			ps.setInt(1, this.getItemId());
			ps.executeUpdate();
			ps.close();
			conn.close();
		} catch (SQLException e) {
			e.printStackTrace();
		}
	}
	
	/**
	 * Generates a VideoGame instance from the results of a database query. 
	 * The query should be something like: 
	 * "SELECT Item.*, VideoGame.* FROM Item INNER JOIN VideoGame ON VideoGame.itemId = Item.itemId ..."
	 * @param rs The ResultSet generated by executing the database query.
	 * @throws SQLException
	 */
	protected VideoGame(ResultSet rs) throws SQLException {
		super(rs);
	}

	@Override
	public String toString() {
		return "Video Game title" + this.getTitle();
	}
	
	public String getType() {
		return "VideoGame";
	}

	@Override
	public int numberOfFields() {
		return Item.NUMFIELDS + this.NUMFIELDS;
	}
}
